services:
  db:
    image: mysql:8.4
    container_name: fantsuam-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ChangeThisPassword123!
      MYSQL_DATABASE: fantsuam
      MYSQL_USER: fantsuam
      MYSQL_PASSWORD: ChangeThisPassword123!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
